### ISSUE TITLE
Calculate a Packet Digest 

### ISSUE THREAD

**Issue by anatolydu** [billchaison/securechannel#1]
Hi Bill,

Very good example !!!
One small issue...

How Packet Digest "0802f92282a7474c" in (5) NetrLogonGetDomainInfo request calculated ?
Can you write an openssl command ?
And can you, please, write a "plain" NetrLogonGetDomainInfo message, before it encrypted.

Thanks.

**Comment by billchaison** [comment]
Hi anatolydu,

Thank you for asking.  The write-up is an example of Secure Channel decryption, it is not meant to be an exhaustive review of Windows internals, such as the packet digest calculation.  You may be able to find that information here https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-NRPC/[MS-NRPC]-151016.pdf
